server:
  port: 8081
  servlet:
    context-path: /mitutucue/springboot/

dubbo:
  application:
    name: dubbo-springboot-consumer
  protocol:
    name: dubbo
    port: 20881
  registry:
    id: nacos-registry
    address: nacos://120.46.223.251:8848
  config-center:
    address: nacos://120.46.223.251:8848
  metadata-report:
    address: nacos://120.46.223.251:8848